#172430232 setup app to deploy on heroku
Stackup-Rwanda/devrepublic-bn-frontend pull request #1
Opened 2020-04-22 10:39 UTC by izzett222

#### What does this PR do?
setup our react app so that we can access it through heroku
#### Description of Task to be completed?
- add express server
- modify the webpack.config.prod
- add the build folder in gitignore
- add the start script
#### How should this be manually tested?
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[ #172430232](Deploy web application to Heroku)
#### Screenshots (if appropriate)
#### Questions:

2020-04-22 10:52 UTC, Ntare22 requested changes

2020-04-22 10:52 UTC, Ntare22 commented on package.json
>    "homepage": "https://github.com/andela/devrepublic-bn-frontend#readme",
this link should change

2020-04-22 11:39 UTC, izzett222 commented on package.json
>    "homepage": "https://github.com/andela/devrepublic-bn-frontend#readme",
let me change it to stackup repo

2020-04-22 12:57 UTC, Ntare22 approved these changes

2020-04-22 13:29 UTC, Baraka-Mugisha approved these changes

2020-04-22 14:09 UTC, bbaime98 approved these changes

2020-04-24 09:45 UTC, jabichris commented on server.js
> +const PORT = process.env.PORT || 4000;
Do you have any idea what will happen if you remove 4000? Please make sure your dotenv is well set.

2020-04-24 09:45 UTC, jabichris commented on server.js
> +const express = require('express');
Make sure your `babel` is well set so that you can use ES6 Import.

2020-04-27 11:41 UTC, izzett222 commented on server.js
> +const express = require('express');
i setup babel, now import can be used

2020-04-27 11:42 UTC, izzett222 commented on server.js
> +const PORT = process.env.PORT || 4000;
I added the dotenv package, the PORT can be read from the env file

2020-04-28 12:46 UTC, merged