Ft requests table 170947497
Stackup-Rwanda/devrepublic-bn-frontend pull request #10
Opened 2020-05-16 20:10 UTC by bbaime98

#### What does this PR do?
- add managers and requesters dashboards
#### Description of Task to be completed?
- add a dashboard route
- create the manager dashboard
- create a requester dashboard
#### How should this be manually tested?
- - log in as a manager then you will be redirected to manager dashboard
- log in as a requester then you will be redirected to requester dashboard
#### Any background context you want to provide?
#### What are the relevant pivotal tracker stories?
- [#170947497](https://www.pivotaltracker.com/story/show/170947497)
#### Screenshots (if appropriate)
#### Questions:

2020-05-22 07:56 UTC, Ntare22 requested changes
Please rebase your work.

2020-05-22 07:57 UTC, Ntare22 reviewed
Create a review app so that we can view your work!

2020-05-22 19:58 UTC, izzett222 requested changes
<img width="236" alt="Screen Shot 2020-05-22 at 21 57 37" src="https://user-images.githubusercontent.com/51261911/82705131-59cefc80-9c77-11ea-9abb-5696bcc9605b.png">
could you add french for the profile link

2020-05-26 12:37 UTC, izzett222 approved these changes

2020-05-26 13:14 UTC, Ntare22 approved these changes

2020-05-26 15:35 UTC, Baraka-Mugisha approved these changes

2020-05-27 09:44 UTC, merged