Ft multiple lang 172499309
Stackup-Rwanda/devrepublic-bn-frontend pull request #6
Opened 2020-05-10 13:16 UTC by bbaime98

#### What does this PR do?
- add  switch between multiple languages feature 
#### Description of Task to be completed?
#### How should this be manually tested?
#### Any background context you want to provide?
#### What are the relevant pivotal tracker stories?
#### Screenshots (if appropriate)
#### Questions:

2020-05-11 09:46 UTC, izzett222 requested changes

2020-05-11 09:46 UTC, izzett222 commented on src/__tests__/shared.js
> +  // });
can you remove the commented code

2020-05-11 09:46 UTC, izzett222 commented on src/views/routes.js
> +    <Route component={sample} />
isn't the name NotFound more understandable than Sample on the not found component

2020-05-11 10:16 UTC, izzett222 reviewed
<img width="598" alt="Screen Shot 2020-05-11 at 12 13 26" src="https://user-images.githubusercontent.com/51261911/81550836-1a540680-9381-11ea-804e-9a6f2133952c.png">
could you add french for the copyright also

2020-05-12 05:30 UTC, Baraka-Mugisha commented
Could you translate the input fields (`email and password`) too??

![french](https://user-images.githubusercontent.com/41383503/81641841-42e00d00-9422-11ea-923e-b5cef3ab1c21.PNG)

2020-05-12 13:17 UTC, bbaime98 commented
> Could you translate the input fields (`email and password`) too??
> 
> ![french](https://user-images.githubusercontent.com/41383503/81641841-42e00d00-9422-11ea-923e-b5cef3ab1c21.PNG)

![image](https://user-images.githubusercontent.com/52517921/81695834-75f6c080-9463-11ea-880d-8c09b79ce28a.png)

2020-05-12 18:18 UTC, jabichris commented on src/__tests__/app.test.js
> +// import { IntlProvider } from 'react-intl';
This is not good for the quality of your code. You should request a review when you are sure that everything is clean. Remove this if you don't need it.

2020-05-12 18:20 UTC, jabichris commented on src/__tests__/shared.js
> +/* eslint-disable import/named */
We agreed that we are not going to disable other eslint rules. Fix this

2020-05-13 08:43 UTC, Ntare22 approved these changes
LGTM

2020-05-13 17:17 UTC, jabichris commented on src/components/App.js
> +/* eslint-disable react/prop-types */
And all the above rules should not be disabled

2020-05-13 17:17 UTC, jabichris commented on src/__mocks__/react-router-dom.js
> +/* eslint-disable react/prop-types */
Can you remove this so that we can merge this PR

2020-05-13 18:00 UTC, merged